title: Nullblock SDK Documentation
description: Comprehensive documentation for Nullblock SDKs and APIs - Advanced Web3 Trading & Agentic Systems
baseurl: "/nullblock-sdk"
url: "https://aetherbytes.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Theme settings
theme: jekyll-theme-cayman

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - sdk/
  - examples/
  - packages/

# Navigation
nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /guides/getting-started/
  - title: API Reference
    url: /api/
  - title: Architecture
    url: /guides/architecture/
  - title: Agents
    url: /guides/agents/
  - title: Trading
    url: /guides/trading/
  - title: Development
    url: /guides/development/
  - title: Examples
    url: https://github.com/aetherBytes/nullblock-sdk/tree/main/examples